export const BACKGROUND_DEFAULT_COLOR = 'var(--colours-common-purple-500)'
export const backgroundColorMap = {
  A: 'var(--colours-common-purple-400)',
  B: 'var(--colours-common-purple-500)',
  C: 'var(--colours-common-purple-600)',
  D: 'var(--colours-common-purple-700)',
  E: 'var(--colours-common-purple-800)',
  F: 'var(--colours-common-purple-900)',
  G: 'var(--colours-common-olive-500)',
  H: 'var(--colours-common-olive-600)',
  I: 'var(--colours-common-olive-700)',
  J: 'var(--colours-common-olive-800)',
  K: 'var(--colours-common-olive-900)',
  L: 'var(--colours-common-blue-500)',
  M: 'var(--colours-common-blue-600)',
  N: 'var(--colours-common-blue-900)',
  O: 'var(--colours-common-pink-500)',
  P: 'var(--colours-common-pink-600)',
  Q: 'var(--colours-common-pink-700)',
  R: 'var(--colours-common-pink-800)',
  S: 'var(--colours-common-pink-900)',
  T: 'var(--colours-common-orange-500)',
  U: 'var(--colours-common-orange-600)',
  V: 'var(--colours-common-orange-700)',
  W: 'var(--colours-common-orange-800)',
  X: 'var(--colours-common-orange-900)',
  Y: 'var(--colours-common-purple-400)',
  Z: 'var(--colours-common-purple-500)',
  '0': 'var(--colours-common-purple-600)',
  '1': 'var(--colours-common-purple-700)',
  '2': 'var(--colours-common-purple-800)',
  '3': 'var(--colours-common-purple-900)',
  '4': 'var(--colours-common-olive-500)',
  '5': 'var(--colours-common-olive-600)',
  '6': 'var(--colours-common-olive-700)',
  '7': 'var(--colours-common-olive-800)',
  '8': 'var(--colours-common-olive-900)',
  '9': 'var(--colours-common-blue-500)'
}
export const badgeColorMap = {
  pink: 'var(--colours-common-pink-500)',
  olive: 'var(--colours-common-olive-500)',
  blue: 'var(--colours-common-blue-500)',
  orange: 'var(--colours-common-orange-500)'
}
